import { type CategoryId, categoryIdFromLabel } from "@/lib/taxonomy";
import { normalizeShopSlug } from "@/lib/slug";

/**
 * Explicitné priradenie obchod → kategória. Jediný zdroj pravdy pre
 * kategorizáciu obchodov — nahrádza keyword matching (inferCategory).
 *
 * Kľúč = kanonický slug obchodu (normalizeShopSlug), t. j. bez TLD:
 * "Alza.sk" aj "Alza" → "alza". Hodnota = CategoryId z lib/taxonomy.ts.
 *
 * Obchod, ktorý tu nie je, sa skúsi zaradiť cez sieťovú kategóriu
 * (eHub/Affial label) v resolveCategory(); inak zostáva nezaradený —
 * nezaradené obchody odhaľuje scripts/audit-categories.ts.
 */
export const SHOP_CATEGORIES: Record<string, CategoryId> = {
  // Elektronika
  alza: "elektronika",
  mall: "elektronika",
  datart: "elektronika",
  nay: "elektronika",
  czc: "elektronika",
  okay: "elektronika",
  samsung: "elektronika",
  apple: "elektronika",
  lenovo: "elektronika",
  hp: "elektronika",
  dell: "elektronika",
  mobilego: "elektronika",
  mobilasz: "elektronika",
  oxe: "elektronika",
  oxepower: "elektronika",
  "eshoptesla-electronics": "elektronika",
  faxcopy: "elektronika",
  "skylink-czsk": "elektronika",
  tinecoshop: "elektronika",
  orange: "elektronika",
  "real-soft": "elektronika",
  ronsoftstore: "elektronika",
  softlite: "elektronika",
  softsrl: "elektronika",
  mmspotrebice: "elektronika",
  avaxeu: "elektronika",
  "gavri-cz-sk-noaton": "elektronika",
  "lunaring-huskczplro": "elektronika",

  // Móda
  zalando: "moda",
  shein: "moda",
  asos: "moda",
  "about-you": "moda",
  answear: "moda",
  zara: "moda",
  hm: "moda",
  bershka: "moda",
  dedoles: "moda",
  zoot: "moda",
  enemiq: "moda",
  "arno-obuv": "moda",
  bonprix: "moda",
  sizeer: "moda",
  mangooutletcombgen: "moda",
  mangooutletcomczcs: "moda",
  mangooutletcomhrhr: "moda",
  mangooutletcomhuhu: "moda",
  mangooutletcomplpl: "moda",
  mangooutletcomroro: "moda",
  mangooutletcomsien: "moda",
  mangooutletcomsken: "moda",
  modivo: "moda",
  "bushman-cz-sk": "moda",
  dobrytextil: "moda",
  zapatos: "moda",
  ecipele: "moda",
  eobutev: "moda",
  "crocs-hrsi": "moda",
  fusakle: "moda",
  "spodni-pradlo": "moda",
  larabags: "moda",
  domibags: "moda",
  "novakabelka-czsk": "moda",
  "kabea-czsk": "moda",
  veroboutique: "moda",
  theywear: "moda",
  bestyle: "moda",
  olaola: "moda",
  "si-housebrand": "moda",
  koze: "moda",
  ccceuhr: "moda",
  eyerim: "moda",
  visionexpress: "moda",
  feelpearls: "moda",
  shoprukahore: "moda",

  // Zdravie
  gymbeam: "zdravie",
  "dr-max": "zdravie",
  drmax: "zdravie",
  herbatica: "zdravie",
  superstrava: "zdravie",
  blendea: "zdravie",
  altevita: "zdravie",
  benulekaren: "zdravie",
  lieky24: "zdravie",
  protein: "zdravie",
  avita: "zdravie",
  eslim: "zdravie",
  stoporex: "zdravie",
  erexan: "zdravie",
  budchlap: "zdravie",
  incacollagen: "zdravie",
  kolagendrink: "zdravie",
  hillvitalshop: "zdravie",
  supershape: "zdravie",
  stressfix: "zdravie",
  "bohatstvo-prirody": "zdravie",
  "6biologico": "zdravie",
  bornature: "zdravie",
  mygreens: "zdravie",
  "vitamin-abc": "zdravie",
  zdravotnidoplnky: "zdravie",
  vivolifeprotein: "zdravie",
  hemniacombg: "zdravie",
  hemniacomcz: "zdravie",
  hemniacomel: "zdravie",
  hemniacomhr: "zdravie",
  hemniacomhu: "zdravie",
  hemniacompl: "zdravie",
  hemniacomro: "zdravie",
  hemniacomsk: "zdravie",
  hemniacomsl: "zdravie",
  konopnafarmaliptov: "zdravie",
  mastichashop: "zdravie",
  masticha: "zdravie",
  dobrapriroda: "zdravie",
  namaximum: "zdravie",
  neohack: "zdravie",
  ejoy: "zdravie",
  ejoytablety: "zdravie",
  vitanella: "zdravie",
  mannavita: "zdravie",
  nutraceutics: "zdravie",
  "breoshop-huskczpl": "zdravie",

  // Krása
  notino: "krasa",
  kosmetikomat: "krasa",
  spaceylon: "krasa",
  nechtovyraj: "krasa",
  kiehls: "krasa",
  shopbeauty: "krasa",
  lapielrs: "krasa",
  lapielshop: "krasa",
  mylapielba: "krasa",
  parfumeshop: "krasa",
  aromaversum: "krasa",
  "luxusni-holeni": "krasa",
  "luxusne-holenie": "krasa",
  zenea: "krasa",
  zeneacare: "krasa",
  hairburst: "krasa",
  "hairburstcomhu-hu": "krasa",
  "laifenshop-huro": "krasa",
  "ulikeshop-huskczplro": "krasa",

  // Šport
  sportisimo: "sport",
  decathlon: "sport",
  intersport: "sport",
  nike: "sport",
  adidas: "sport",
  shox: "sport",
  belda: "sport",
  tpmove: "sport",
  sportby: "sport",
  "4fstore": "sport",
  ironaesthetics: "sport",
  futbalovedarceky: "sport",
  fotbalovydarek: "sport",
  focicipobolt: "sport",
  "2sport-czsk": "sport",

  // Bývanie
  ikea: "byvanie",
  hornbach: "byvanie",
  obi: "byvanie",
  "e-matrac": "byvanie",
  artofhome: "byvanie",
  "li-go": "byvanie",
  "4home": "byvanie",
  dekoria: "byvanie",
  mojnabytok: "byvanie",
  mujnabytek: "byvanie",
  inpostele: "byvanie",
  "i-zahradnynabytok": "byvanie",
  "i-zahradninabytek": "byvanie",
  houseland: "byvanie",
  homepoint: "byvanie",
  hauzi: "byvanie",
  lahome: "byvanie",
  mybesthome: "byvanie",
  domio: "byvanie",
  dekoraciedobytu: "byvanie",
  "dizajnove-doplnky": "byvanie",
  zarovky: "byvanie",
  ledvonal: "byvanie",
  feny24: "byvanie",
  filtrydokonvice: "byvanie",
  "luxusni-noze": "byvanie",
  superkotlik: "byvanie",
  emmezeta: "byvanie",
  otthonshop: "byvanie",
  "elmich-cz": "byvanie",
  dobrepodlahy: "byvanie",
  slnecnaplachta: "byvanie",
  napvitorlawebshop: "byvanie",
  sungardensail: "byvanie",
  zagielprzeciwsloneczny: "byvanie",
  panzaparasolar: "byvanie",
  baumax: "byvanie",
  "vypredaj-regalov": "byvanie",
  "vyprodej-regalu": "byvanie",
  aquatopshop: "byvanie",
  piumo: "byvanie",
  nabbi: "byvanie",
  sentop: "byvanie",
  sentopeu: "byvanie",
  ajprodukty: "byvanie",
  rostlinkovo: "byvanie",
  "dxracer-cz-skkancelarskezidle": "byvanie",
  "diablochairs-europe": "byvanie",
  remoska: "byvanie",
  cisteoblecenie: "byvanie",
  cisteobleceni: "byvanie",
  ajtorendeles: "byvanie",
  e4home: "byvanie",
  solapoint: "byvanie",
  solapointch: "byvanie",
  lumories: "byvanie",
  sparkl: "byvanie",

  // Potraviny
  lidl: "potraviny",
  kaufland: "potraviny",
  tesco: "potraviny",
  billa: "potraviny",
  rohlik: "potraviny",
  coffeein: "potraviny",
  napojelasky: "potraviny",
  simplywines: "potraviny",
  alkoshop: "potraviny",
  tchibo: "potraviny",
  medaren: "potraviny",
  morethanhoney: "potraviny",
  scoby: "potraviny",
  moyamatcha: "potraviny",
  matchaday: "potraviny",
  kampotskekorenie: "potraviny",
  kampotskypepr: "potraviny",
  vegmart: "potraviny",
  zdravestravovani: "potraviny",
  "sonnentorcomcs-cz": "potraviny",
  milenialcafe: "potraviny",
  lacapsuleria: "potraviny",
  edesstory: "potraviny",
  asiashop: "potraviny",

  // Deti
  dadaboom: "deti",
  "kojenecke-obleceni": "deti",
  "milinko-oblecenie": "deti",
  bubulakovo: "deti",
  "4kids": "deti",
  bambule: "deti",
  mamido: "deti",
  babadzsungel: "deti",
  pajkospajtas: "deti",
  zubicvila: "deti",
  pismozubicvile: "deti",
  pismodedamrazars: "deti",
  pismodjedabozicnjaka: "deti",
  "legocomcs-cz": "deti",
  "legocomhu-hu": "deti",
  "legocompl-pl": "deti",
  "legocomro-ro": "deti",
  oxybag: "deti",
  kufrik: "deti",
  "divadlo-kufrik": "deti",

  // Cestovanie
  booking: "cestovanie",
  airbnb: "cestovanie",
  invia: "cestovanie",
  travelino: "cestovanie",

  // Knihy
  martinus: "knihy",
  bux: "knihy",
  "panta-rhei": "knihy",
  szalaykonyvek: "knihy",
  teakiado: "knihy",
  inlibrionline: "knihy",
  dotykslov: "knihy",

  // Iné — erotika, zvieratá, auto-moto, marketplace, darčeky
  temu: "ine",
  wish: "ine",
  intimnenakupy: "ine",
  eros: "ine",
  "69shop": "ine",
  lovesexshop: "ine",
  szexshop: "ine",
  erotikashow: "ine",
  titkossexshop: "ine",
  goodlove: "ine",
  vagyaim: "ine",
  desirel: "ine",
  zoohit: "ine",
  "abc-zoo": "ine",
  "abc-zoosklep": "ine",
  vsepropejska: "ine",
  okfish: "ine",
  "dobra-miska": "ine",
  cricksydog: "ine",
  cricksydoggr: "ine",
  zoonet: "ine",
  budsforbuddiescombg: "ine",
  budsforbuddiescomcz: "ine",
  budsforbuddiescomel: "ine",
  budsforbuddiescomhr: "ine",
  budsforbuddiescomhu: "ine",
  budsforbuddiescompl: "ine",
  budsforbuddiescomro: "ine",
  budsforbuddiescomrs: "ine",
  budsforbuddiescomsk: "ine",
  budsforbuddiescomsl: "ine",
  autovybava: "ine",
  autozulu: "ine",
  originalnipneu: "ine",
  gekkogumi: "ine",
  gumisfutar: "ine",
  garazstechnika: "ine",
  allegro: "ine",
  "e-armyshop": "ine",
  brasty: "ine",
  "eobaly-czsk": "ine",
  artmie: "ine",
  "semena-marihuany": "ine",
  "luxusne-pera": "ine",
  "luxusni-pera": "ine",
  ploom: "ine",
  nejlevnejsizbozi: "ine",
  manmall: "ine",
  tozax: "ine",
  pobalsa: "ine",
};

export interface ResolveCategoryInput {
  /** Zobrazované meno obchodu ("Alza.sk", "Dr. Max") */
  name?: string | null;
  /** Kanonický slug, ak ho volajúci už má */
  slug?: string | null;
  /** Doména obchodu ("alza.sk") */
  domain?: string | null;
  /** Label kategórie zo siete (eHub CZ label, Affial slug, SK label) */
  networkCategory?: string | null;
}

/**
 * Zaradí obchod do kanonickej kategórie. Poradie: explicitná mapa
 * (slug → meno → doména), potom mapovanie sieťového labelu.
 * Vracia null, keď obchod nevieme zaradiť — ŽIADNE hádanie z kľúčových slov.
 */
export function resolveCategory(input: ResolveCategoryInput): CategoryId | null {
  const keys = [
    input.slug || "",
    input.name ? normalizeShopSlug(input.name) : "",
    input.domain ? normalizeShopSlug(input.domain) : "",
  ];
  for (const key of keys) {
    if (key && SHOP_CATEGORIES[key]) return SHOP_CATEGORIES[key];
  }
  return categoryIdFromLabel(input.networkCategory);
}
