import type { HkFeedDef } from "./types";
import { inferCurrencyCodeForConfiguredFeed } from "@/lib/price";

const AFFIAL_AID = process.env.AFFIAL_ACCOUNT_ID ?? "6202d95ce406b";

// 52 overených Heureka XML feedov (SHOP/SHOPITEM formát, PRODUCTNAME + PRICE_VAT + URL, overené 2026-07-02)
// Bezpečnostné čistenie 2026-07-02: vyradené bottle-store.sk (alkohol) a vaporism.cz (vape/nikotín)
// Google Shopping feedy vyradené (kosmetikomat.sk, blendea, nechtovyraj.sk)
// li-go.cz má popri Google feede aj validný /heureka/export/products.xml — pridaný
// tpmove.sk vyradený — universal.xml má SHOPITEM bez PRODUCTNAME (parser ho nevie spracovať)
// Feedy bez Affial programu majú affiliateUrl: null — tlačidlo vedie na URL produktu z feedu
type StaticFeedDef = Omit<HkFeedDef, "currencyCode"> & { currencyCode?: HkFeedDef["currencyCode"] };

const _FEEDS: StaticFeedDef[] = [
  // bývanie
  {
    id: "e-matrac-sk",
    url: "https://www.e-matrac.sk/heureka/export/products.xml",
    domain: "e-matrac.sk",
    category: "byvanie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=7333ef8f",
  },
  {
    id: "fotoobrazyzplatna-sk",
    url: "https://www.fotoobrazyzplatna.cz/export/heureka.xml?lang=sk",
    domain: "fotoobrazyzplatna.sk",
    category: "byvanie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=86e29062",
  },
  // šport
  {
    id: "shox-sk",
    url: "https://www.shox.sk/wp-content/uploads/product-feeds/heureka_sk.xml",
    domain: "shox.sk",
    category: "sport",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=bf2d48e7",
  },
  {
    id: "shox-cz",
    url: "https://www.shox.cz/wp-content/uploads/product-feeds/heureka_cz.xml",
    domain: "shox.cz",
    category: "sport",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=796cb0f7",
  },
  {
    id: "belda-sk",
    url: "https://www.belda.sk/heureka/export/products.xml",
    domain: "belda.sk",
    category: "sport",
    affiliateUrl: null,
  },
  // zdravie
  {
    id: "superstrava-sk",
    url: "https://www.superstrava.sk/heureka/export/products.xml",
    domain: "superstrava.sk",
    category: "zdravie",
    affiliateUrl: "https://www.superstrava.sk/?utm_medium=affiliate&utm_campaign=affial.com&utm_source=pap&a_aid=6202d95ce406b&a_bid=02bd6c6c",
  },
  {
    id: "altevita-sk",
    url: "https://www.altevita.sk/heureka/export/products.xml",
    domain: "altevita.sk",
    category: "zdravie",
    affiliateUrl: "https://altevita.sk/?utm_medium=affiliate&utm_campaign=affial.com&utm_source=pap&a_aid=6202d95ce406b&a_bid=8bbcdb52",
  },
  {
    id: "herbatica-sk",
    url: "http://www.herbatica.sk/heureka/export/products.xml",
    domain: "herbatica.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "neurinu-cz",
    url: "https://www.neurinu.cz/wp-content/uploads/xml/heureka_1.xml",
    domain: "neurinu.cz",
    category: "zdravie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=1b6da38c",
  },
  // krása
  {
    id: "spaceylon-sk",
    url: "https://www.spaceylon.sk/fotky44397/xml/heureka_sk.xml",
    domain: "spaceylon.sk",
    category: "krasa",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=8dd268c9",
  },
  // móda
  {
    id: "enemiq-sk",
    url: "https://www.enemiq.sk/heureka/export/products.xml",
    domain: "enemiq.sk",
    category: "moda",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=0fd905ea",
  },
  {
    id: "enemiq-cz",
    url: "https://www.enemiq.cz/heureka/export/products.xml",
    domain: "enemiq.cz",
    category: "moda",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=584e8d61",
  },
  {
    id: "arno-obuv-sk",
    url: "https://www.arno-obuv.sk/feed/heureka",
    domain: "arno-obuv.sk",
    category: "moda",
    affiliateUrl: "https://www.arno-obuv.sk/?utm_medium=affiliate&utm_campaign=affial.com&utm_source=pap&a_aid=6202d95ce406b&a_bid=e6456574",
  },
  // deti
  {
    id: "dadaboom-sk",
    url: "https://www.dadaboom.sk/feed-heureka-tl7hkzvm56.xml",
    domain: "dadaboom.sk",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "kojenecke-obleceni-eu",
    url: "https://www.kojenecke-obleceni.eu/export/heureka/472b02a8-25a0-4294-bec4-055a24411fd3",
    domain: "kojenecke-obleceni.eu",
    category: "deti",
    affiliateUrl: null,
  },
  // potraviny
  {
    id: "ajala-cz",
    url: "https://www.ajala.cz/heureka/export/products.xml",
    domain: "ajala.cz",
    category: "potraviny",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=6ff3c951",
  },
  // knihy
  {
    id: "togga-cz",
    url: "https://www.togga.cz/heureka/export/products.xml",
    domain: "togga.cz",
    category: "knihy",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=6c0959fa",
  },
  // iné
  {
    id: "happylu-cz",
    url: "https://www.happylu.cz/heureka/export/products.xml",
    domain: "happylu.cz",
    category: "ine",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=78943379",
  },
  {
    id: "auto123-sk",
    url: "https://auto123.sk/media/feeds/heureka.xml",
    domain: "auto123.sk",
    category: "ine",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=d7c0bd56",
  },
  // vaporism.cz vyradený 2026-07-02 — e-cigarety a nikotínové e-liquidy (bezpečnostné čistenie)

  // ===== Rozšírenie na ~50 feedov (overené 2026-07-02) =====
  // bývanie / domácnosť
  {
    id: "li-go-cz",
    url: "https://www.li-go.cz/heureka/export/products.xml",
    domain: "li-go.cz",
    category: "byvanie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=d344a869",
  },
  {
    id: "artofhome-cz",
    url: "https://www.artofhome.cz/heureka/export/products.xml",
    domain: "artofhome.cz",
    category: "byvanie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=9612d676",
  },
  {
    id: "nanospace-cz",
    url: "https://www.nanospace.cz/heureka/export/products.xml",
    domain: "nanospace.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "kulina-sk",
    url: "https://www.kulina.sk/heureka/export/products.xml",
    domain: "kulina.sk",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "kulina-cz",
    url: "https://www.kulina.cz/heureka/export/products.xml",
    domain: "kulina.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  // bottle-store.sk vyradený 2026-07-02 — alkohol e-shop (bezpečnostné čistenie)
  {
    id: "mafecandles-cz",
    url: "https://www.mafecandles.cz/heureka/export/products.xml",
    domain: "mafecandles.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  // zdravie
  {
    id: "zelenazeme-cz",
    url: "https://www.zelenazeme.cz/heureka/export/products.xml",
    domain: "zelenazeme.cz",
    category: "zdravie",
    affiliateUrl: null,
    // bezpečnostné čistenie: CBD kvety/herba a vaporizéry (vrátane príslušenstva) sa neimportujú
    exclude: ["cbd flower", "cbd kvet", "cbd herba", "vaporiz", "cartridge"],
  },
  {
    id: "matchatea-bio",
    url: "https://www.matchatea.bio/heureka/export/products.xml",
    domain: "matchatea.bio",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "puravidashop-cz",
    url: "https://www.puravidashop.cz/heureka/export/products.xml",
    domain: "puravidashop.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  // krása
  {
    id: "angrybeards-sk",
    url: "https://www.angrybeards.sk/heureka/export/products.xml",
    domain: "angrybeards.sk",
    category: "krasa",
    affiliateUrl: null,
  },
  {
    id: "angrybeards-cz",
    url: "https://www.angrybeards.cz/heureka/export/products.xml",
    domain: "angrybeards.cz",
    category: "krasa",
    affiliateUrl: null,
  },
  {
    id: "creammy-cz",
    url: "https://www.creammy.cz/heureka/export/products.xml",
    domain: "creammy.cz",
    category: "krasa",
    affiliateUrl: null,
  },
  // šport
  {
    id: "vifsports-cz",
    url: "https://www.vifsports.cz/heureka/export/products.xml",
    domain: "vifsports.cz",
    category: "sport",
    affiliateUrl: null,
  },
  // deti
  {
    id: "benlemi-sk",
    url: "https://www.benlemi.sk/heureka/export/products.xml",
    domain: "benlemi.sk",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "slnieckovo-sk",
    url: "https://www.slnieckovo.sk/heureka/export/products.xml",
    domain: "slnieckovo.sk",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "elisdesign-cz",
    url: "https://www.elisdesign.cz/heureka/export/products.xml",
    domain: "elisdesign.cz",
    category: "deti",
    affiliateUrl: null,
  },
  // hobby
  {
    id: "aeromodel-sk",
    url: "https://www.aeromodel.sk/heureka/export/products.xml",
    domain: "aeromodel.sk",
    category: "hobby",
    affiliateUrl: null,
  },
  {
    id: "mincmistr-cz",
    url: "https://www.mincmistr.cz/heureka/export/products.xml",
    domain: "mincmistr.cz",
    category: "hobby",
    affiliateUrl: null,
  },
  // záhrada
  {
    id: "mojerosty-sk",
    url: "https://www.mojerosty.sk/heureka/export/products.xml",
    domain: "mojerosty.sk",
    category: "zahrada",
    affiliateUrl: null,
  },
  // móda
  {
    id: "daponti-sk",
    url: "https://www.daponti.sk/heureka/export/products.xml",
    domain: "daponti.sk",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "miabella-cz",
    url: "https://www.miabella.cz/heureka/export/products.xml",
    domain: "miabella.cz",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "tiami-cz",
    url: "https://www.tiami.cz/heureka/export/products.xml",
    domain: "tiami.cz",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "lobey-cz",
    url: "https://www.lobey.cz/heureka/export/products.xml",
    domain: "lobey.cz",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "salted-cz",
    url: "https://www.salted.cz/heureka/export/products.xml",
    domain: "salted.cz",
    category: "moda",
    affiliateUrl: null,
  },
  // potraviny
  {
    id: "kofi-sk",
    url: "https://www.kofi.sk/heureka/export/products.xml",
    domain: "kofi.sk",
    category: "potraviny",
    affiliateUrl: null,
  },
  {
    id: "coffeesheep-sk",
    url: "https://www.coffeesheep.sk/heureka/export/products.xml",
    domain: "coffeesheep.sk",
    category: "potraviny",
    affiliateUrl: null,
  },
  {
    id: "cokoladovnatroubelice-cz",
    url: "https://www.cokoladovnatroubelice.cz/heureka/export/products.xml",
    domain: "cokoladovnatroubelice.cz",
    category: "potraviny",
    affiliateUrl: null,
  },
  // iné
  {
    id: "fabulo-sk",
    url: "https://www.fabulo.sk/heureka/export/products.xml",
    domain: "fabulo.sk",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "darbox-sk",
    url: "https://www.darbox.sk/heureka/export/products.xml",
    domain: "darbox.sk",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "heliumking-sk",
    url: "https://www.heliumking.sk/heureka/export/products.xml",
    domain: "heliumking.sk",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "plzr-sk",
    url: "https://www.plzr.sk/heureka/export/products.xml",
    domain: "plzr.sk",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "keeostore-cz",
    url: "https://www.keeostore.cz/heureka/export/products.xml",
    domain: "keeostore.cz",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "trivjednom-cz",
    url: "https://www.3v1trivjednom.cz/heureka/export/products.xml",
    domain: "3v1trivjednom.cz",
    category: "ine",
    affiliateUrl: null,
  },
  // ===== Rozsirenie feedov 2026-07-09 =====
  // elektronika
  {
    id: "carneo-sk",
    url: "https://www.carneo.sk/heureka/export/products.xml",
    domain: "carneo.sk",
    category: "elektronika",
    affiliateUrl: null,
  },
  // hobby / naradie
  {
    id: "naradihned-sk",
    url: "https://www.naradihned.sk/heureka/export/products.xml",
    domain: "naradihned.sk",
    category: "hobby",
    affiliateUrl: null,
  },
  {
    id: "mp-kovania-sk",
    url: "https://www.mp-kovania.sk/export/heureka.xml",
    domain: "mp-kovania.sk",
    category: "hobby",
    affiliateUrl: null,
  },
  {
    id: "lacne-farby-laky-sk",
    url: "https://www.lacne-farby-laky.sk/export/heureka.xml",
    domain: "lacne-farby-laky.sk",
    category: "hobby",
    affiliateUrl: null,
  },
  // byvanie / domacnost
  {
    id: "sedet-cz",
    url: "https://www.sedet.cz/export/heureka/feed.xml",
    domain: "sedet.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "cistedrevo-sk",
    url: "https://www.cistedrevo.sk/heureka/export/products.xml",
    domain: "cistedrevo.sk",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "perfetto-sk",
    url: "https://www.perfetto.sk/export/heureka.xml",
    domain: "perfetto.sk",
    category: "byvanie",
    affiliateUrl: null,
  },
  // deti
  {
    id: "kociky-sk",
    url: "https://www.kociky.sk/heureka/export/products.xml",
    domain: "kociky.sk",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "bezvaplenky-cz",
    url: "https://www.bezvaplenky.cz/heureka/export/products.xml",
    domain: "bezvaplenky.cz",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "elektrickeauticko-cz",
    url: "https://feeds.mergado.com/elektricka-auticka-heureka-cz-cz-1-1ab00de3fd9779709cc451d089fbd3b0.xml",
    domain: "elektrickeauticko.cz",
    category: "deti",
    affiliateUrl: null,
  },
  // zdravie
  {
    id: "brainmarket-sk",
    url: "https://www.brainmarket.sk/heureka/export/products.xml",
    domain: "brainmarket.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "brainmarket-cz",
    url: "https://www.brainmarket.cz/heureka/export/products.xml",
    domain: "brainmarket.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "organicmarket-cz",
    url: "https://www.organicmarket.cz/heureka/export/products.xml",
    domain: "organicmarket.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "powerlogy-com",
    url: "https://powerlogy.com/wp-content/uploads/wpallexport/exports/df3bd20ee04ad4a7874c46ee151b165f/current-CRON-heureka-xml-feed.xml",
    domain: "powerlogy.com",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "bornature-sk",
    url: "https://www.bornature.sk/heureka/export/products.xml",
    domain: "bornature.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "avita-sk",
    url: "https://avita.sk/heureka/export/products.xml",
    domain: "avita.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "medaren-sk",
    url: "https://www.medaren.sk/heureka/export/products.xml",
    domain: "medaren.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  // krasa
  {
    id: "kosmetikomat-cz",
    url: "https://www.kosmetikomat.cz/heureka/export/products.xml",
    domain: "kosmetikomat.cz",
    category: "krasa",
    affiliateUrl: null,
  },
  {
    id: "rajnehtu-cz",
    url: "https://www.rajnehtu.cz/heureka/export/products.xml",
    domain: "rajnehtu.cz",
    category: "krasa",
    affiliateUrl: null,
  },
  {
    id: "hellococo-sk",
    url: "https://www.hellococo.sk/heureka/export/products.xml",
    domain: "hellococo.sk",
    category: "krasa",
    affiliateUrl: null,
  },
  // Discovery 2026-07: obchody z Dognet/Affial sietí s validným Heureka feedom
  // (overené parse + produkty). Dognet shopy: affiliateUrl null → Heureka haff
  // fallback (obchod je na Heureke, EAN nájde produkt). Affial shopy: Affial link.
  {
    id: "tpmove-sk",
    url: "https://www.tpmove.sk/heureka/export/products.xml",
    domain: "tpmove.sk",
    category: "zdravie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=588d5af3",
  },
  {
    id: "remoska-sk",
    url: "https://www.remoska.sk/heureka/export/products.xml",
    domain: "remoska.sk",
    category: "byvanie",
    affiliateUrl: "https://login.affial.com/scripts/click.php?a_aid=6202d95ce406b&desturl=https%3A%2F%2Fwww.remoska.sk%2F",
  },
  {
    id: "kolagendrink-cz",
    url: "https://kolagendrink.cz/heureka/export/products.xml",
    domain: "kolagendrink.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "kolagendrink-sk",
    url: "https://kolagendrink.sk/heureka/export/products.xml",
    domain: "kolagendrink.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "vivolifeprotein-cz",
    url: "https://www.vivolifeprotein.cz/heureka/export/products.xml",
    domain: "vivolifeprotein.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "divadlo-kufrik-sk",
    url: "https://www.divadlo-kufrik.sk/heureka/export/products.xml",
    domain: "divadlo-kufrik.sk",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "morethanhoney-cz",
    url: "https://www.morethanhoney.cz/heureka/export/products.xml",
    domain: "morethanhoney.cz",
    category: "potraviny",
    affiliateUrl: null,
  },
  {
    id: "kufrik-cz",
    url: "https://kufrik.cz/heureka/export/products.xml",
    domain: "kufrik.cz",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "hellococo-cz",
    url: "https://www.hellococo.cz/heureka/export/products.xml",
    domain: "hellococo.cz",
    category: "krasa",
    affiliateUrl: null,
  },
  {
    id: "baktoma-sk",
    url: "https://www.baktoma.sk/heureka/export/products.xml",
    domain: "baktoma.sk",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "bornature-cz",
    url: "https://www.bornature.cz/heureka/export/products.xml",
    domain: "bornature.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "izerex-sk",
    url: "https://www.izerex.sk/feed/heureka",
    domain: "izerex.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "mastichashop-cz",
    url: "https://www.mastichashop.cz/heureka/export/products.xml",
    domain: "mastichashop.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "hillvitalshop-cz",
    url: "https://www.hillvitalshop.cz/heureka/export/products.xml",
    domain: "hillvitalshop.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "milenialcafe-cz",
    url: "https://www.milenialcafe.cz/heureka/export/products.xml",
    domain: "milenialcafe.cz",
    category: "potraviny",
    affiliateUrl: null,
  },
  {
    id: "milenialcafe-sk",
    url: "https://www.milenialcafe.sk/heureka/export/products.xml",
    domain: "milenialcafe.sk",
    category: "potraviny",
    affiliateUrl: null,
  },
  {
    id: "pravaklobasa-cz",
    url: "https://pravaklobasa.cz/heureka/export/products.xml",
    domain: "pravaklobasa.cz",
    category: "potraviny",
    affiliateUrl: null,
  },
  // Discovery 2026-07 (2. dávka — domény z kupónových cache)
  {
    id: "tozax-cz",
    url: "https://www.tozax.cz/heureka/export/products.xml",
    domain: "tozax.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "olaola-cz",
    url: "https://www.olaola.cz/feed/heureka",
    domain: "olaola.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "avita-cz",
    url: "https://www.avita.cz/heureka/export/products.xml",
    domain: "avita.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  // Discovery 2026-07 (3. dávka — Affial panel Kampaně, 130 kampaní)
  {
    id: "arno-cz",
    url: "https://www.arno.cz/feed/heureka",
    domain: "arno.cz",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "tokrahome-cz",
    url: "https://www.tokrahome.cz/heureka/export/products.xml",
    domain: "tokrahome.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "zdravibezchemie-cz",
    url: "https://www.zdravibezchemie.cz/heureka/export/products.xml",
    domain: "zdravibezchemie.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "boruvkovykopecek-cz",
    url: "https://www.boruvkovykopecek.cz/heureka/export/products.xml",
    domain: "boruvkovykopecek.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "nupreme-com",
    url: "https://www.nupreme.com/heureka/export/products.xml",
    domain: "nupreme.com",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "bagniaristore-cz",
    url: "https://www.bagniaristore.cz/heureka/export/products.xml",
    domain: "bagniaristore.cz",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "clovecinahra-sk",
    url: "https://www.clovecinahra.sk/heureka/export/products.xml",
    domain: "clovecinahra.sk",
    category: "hobby",
    affiliateUrl: null,
  },
  // ===== Affial CSV export 2026-07-16 (24 feedov, validované scripts/validate-affial-feeds.ts) =====
  // Vyradené: alkohol (drinkcentrum.*), vape (vaporism.cz), elektrické obojky pre psy,
  // zahraničné trhy (.hu/.pl), 404/timeout/nepodporovaný formát feedy.
  // zdravie
  {
    id: "namaximum-cz",
    url: "https://greenmedical.venalio.com/feeds/heureka?websiteLanguageId=2&secretKey=6rh8m9v0idfjbx4jhdkw7n4wo4wi75y1rt70y12x",
    domain: "namaximum.cz",
    category: "zdravie",
    affiliateUrl: "https://login.affial.com/scripts/click.php?a_aid=6202d95ce406b&desturl=https%3A%2F%2Fnamaximum.cz%2F",
  },
  {
    id: "namaximum-sk",
    url: "https://greenmedical.venalio.com/feeds/heureka?websiteLanguageId=1&secretKey=gfcqk793m9iifpodwnssfh9s7sdnfqryy2zshrfw",
    domain: "namaximum.sk",
    category: "zdravie",
    affiliateUrl: "https://login.affial.com/scripts/click.php?a_aid=6202d95ce406b&desturl=https%3A%2F%2Fnamaximum.sk%2F",
  },
  {
    id: "chiashake-cz",
    url: "https://www.chiashake.cz/feed-heureka-2lkmu0rfo9.xml",
    domain: "chiashake.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "chiashake-sk",
    url: "https://www.chiashake.sk/feed-heureka-2lkmu0rfo9.xml",
    domain: "chiashake.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "mixslim-cz",
    url: "https://www.mixslim.cz/feed-heureka-2lkmu0rfo9.xml",
    domain: "mixslim.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "mixslim-sk",
    url: "https://www.mixslim.sk/feed-heureka-2lkmu0rfo9.xml",
    domain: "mixslim.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "powerlogy-cz",
    url: "https://powerlogy.cz/wp-content/uploads/wpallexport/exports/d35fe88e772017e42c6beccdc8137dea/current-CRON-heureka-xml-feed.xml",
    domain: "powerlogy.cz",
    category: "zdravie",
    affiliateUrl: "https://powerlogy.cz/?utm_medium=affiliate&utm_campaign=affial.com&utm_source=pap&a_aid=6202d95ce406b&a_bid=98b6eb54",
  },
  {
    id: "skinny-cz",
    url: "https://www.skinny.cz/heureka/export/products.xml",
    domain: "skinny.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "paleomarket-cz",
    url: "https://paleomarket.cz/wp-content/xml/heureka_1.xml",
    domain: "paleomarket.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "vianutra-sk",
    url: "https://vianutra.com/wp-content/uploads/xml/heureka_1.xml",
    domain: "vianutra.sk",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "simplymix-com",
    url: "https://www.simplymix.com/heureka/export/products.xml",
    domain: "simplymix.com",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "neohack-sk",
    url: "https://storage.feedyio.com/neohack.myshopify.com/671212466f8a0b6c4bb94f68.xml",
    domain: "neohack.sk",
    category: "zdravie",
    affiliateUrl: "https://login.affial.com/scripts/click.php?a_aid=6202d95ce406b&desturl=https%3A%2F%2Fwww.neohack.sk%2F",
  },
  {
    id: "raciolka-cz",
    url: "https://www.raciolka.cz/data-xml/modul-heureka/heureka-read.php?shop=1&type=productscz&token=d450d47880",
    domain: "raciolka.cz",
    category: "zdravie",
    affiliateUrl: "https://login.affial.com/scripts/8m338kc?a_aid=6202d95ce406b&a_bid=3843b610",
  },
  // krasa
  {
    id: "wetyzo-cz",
    url: "https://www.wetyzo.cz/heureka/export/products.xml",
    domain: "wetyzo.cz",
    category: "krasa",
    affiliateUrl: null,
  },
  // byvanie
  {
    id: "kreativnastena-sk",
    url: "https://kreativnastena.sk/erp/impexp/specialexport/heureka/",
    domain: "kreativnastena.sk",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "remoska-eu",
    url: "https://shop.remoska.eu/heureka/export/products.xml",
    domain: "remoska.eu",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "drevona-sk",
    url: "https://feeds.mergado.com/drevona-sk-heureka-sk-2-11827febc2dd0115753d06ae58e8140f.xml",
    domain: "drevona.sk",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "fotoobrazyzplatna-cz",
    url: "https://www.fotoobrazyzplatna.cz/export/heureka.xml?lang=cs",
    domain: "fotoobrazyzplatna.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  // deti
  {
    id: "dadaboom-cz",
    url: "https://www.dadaboom.cz/feed-heureka-tl7hkzvm56.xml",
    domain: "dadaboom.cz",
    category: "deti",
    affiliateUrl: null,
  },
  {
    id: "ponnie-eu",
    url: "https://www.ponnie.eu/cz/feed-heureka-6cnf7vmpez.xml",
    domain: "ponnie.eu",
    category: "deti",
    affiliateUrl: null,
  },
  // ine
  {
    id: "jshop-cz",
    url: "https://www.jshop.cz/xml/heureka2.xml",
    domain: "jshop.cz",
    category: "ine",
    affiliateUrl: null,
  },
  {
    id: "24365-cz",
    url: "https://feeds.mergado.com/sapro-heureka-cz-produktovy-cz-1-a5e24c5f285390452ffb508ce6d1fd59.xml",
    domain: "24365.cz",
    category: "ine",
    affiliateUrl: null,
  },
  // sport
  {
    id: "florbal4u-com",
    url: "https://feeds.mergado.com/florbal4u-com-heureka-sk-2-3c5da768a57cc465690aa1463fdda2b1.xml",
    domain: "florbal4u.com",
    category: "sport",
    affiliateUrl: null,
  },
  {
    id: "florbal4u-cz",
    url: "https://feeds.mergado.com/florbal4u-cz-heureka-cz-33d6ee3fba451e6099fb745aa90dce25.xml",
    domain: "florbal4u.cz",
    category: "sport",
    affiliateUrl: null,
  },
  // ===== Affial CSV recovery + pattern discovery 2026-07-16 (scripts/discover-affial-feeds.ts) =====
  // 2. kolo s reálnymi limitmi importu (60 s / 60 MB): recovered false-negatívy
  // (irisimo/beldasport/designpropaganda) + štandardné Heureka cesty pre obchody,
  // ktorých CSV URL 404/timeout/zlý formát.
  {
    id: "irisimo-sk",
    url: "https://www.irisimo.sk/export/heureka",
    domain: "irisimo.sk",
    category: "moda",
    affiliateUrl: null,
  },
  {
    id: "designpropaganda-cz",
    url: "https://www.designpropaganda.cz/heurekacz.xml",
    domain: "designpropaganda.cz",
    category: "byvanie",
    affiliateUrl: "https://www.designpropaganda.cz/?utm_medium=affiliate&utm_campaign=affial.com&utm_source=pap&a_aid=6202d95ce406b&a_bid=20a6b859",
  },
  {
    id: "beldasport-cz",
    url: "https://www.beldasport.cz/heureka/export/products.xml",
    domain: "beldasport.cz",
    category: "sport",
    affiliateUrl: null,
  },
  {
    id: "eshopmania-cz",
    url: "https://www.eshopmania.cz/heureka/export/products.xml",
    domain: "eshopmania.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "herbavia-cz",
    url: "https://www.herbavia.cz/heureka/export/products.xml",
    domain: "herbavia.cz",
    category: "zdravie",
    affiliateUrl: null,
  },
  {
    id: "decohouse-cz",
    url: "https://www.decohouse.cz/heureka/export/products.xml",
    domain: "decohouse.cz",
    category: "byvanie",
    affiliateUrl: null,
  },
  {
    id: "clovecinahra-cz",
    url: "https://www.clovecinahra.cz/heureka/export/products.xml",
    domain: "clovecinahra.cz",
    category: "ine",
    affiliateUrl: null,
  },
];

export const HEUREKA_FEEDS: HkFeedDef[] = _FEEDS.map((f) => ({
  ...f,
  affiliateUrl: f.affiliateUrl ? f.affiliateUrl.replace("6202d95ce406b", AFFIAL_AID) : null,
  currencyCode: f.currencyCode ?? inferCurrencyCodeForConfiguredFeed(f.domain),
}));
